### ISSUE TITLE
binding.gyp not found when building on Amazon Linux AMI

### ISSUE THREAD

**Issue by jlines** [christkv/bson-ext#12]
Here are the contents of the builderror.log files. Has anyone see this issue before? It looks like its trying to run mac specific code for some reason.

./application/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/builderror.log
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

./application/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/builderror.log
gyp: binding.gyp not found (cwd: /tmp/deployment/application/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/elasticbeanstalk/node-install/node-v0.12.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.14.35-28.38.amzn1.x86_64
gyp ERR! command "node" "/opt/elasticbeanstalk/node-install/node-v0.12.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/deployment/application/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

  npm ERR! node v0.12.2
  npm ERR! npm  v2.7.4
  npm ERR! code ELIFECYCLE
  npm ERR! bson-ext@0.1.3 install: `node-pre-gyp install --fallback-to-build`
  npm ERR! Exit status 1

**Comment by skyle143** [comment]
I'm seeing the exact same issue on amazon linux ami. To add a little more context, the app is build on a mac and deployed to elastic beanstalk. It then runs an npm rebuild (not npm install). That's when we get the following errors.

Here is the output of npm-debug.log:

info bson-ext@0.1.4 Failed to exec install script
error bson-ext@0.1.4 install: `node-pre-gyp install --fallback-to-build`
error Exit status 8
error Failed at the bson-ext@0.1.4 install script.
error This is most likely a problem with the bson-ext package,
error not with npm itself.
error Tell the author that this fails on your system:
error     node-pre-gyp install --fallback-to-build
error You can get their info via:
error     npm owner ls bson-ext
error There is likely additional logging output above.
error System Linux 3.10.57-57.140.amzn1.x86_64
error command "/opt/elasticbeanstalk/node-install/node-v0.10.26-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v0.10.26-linux-x64/bin/npm" "--production" "rebuild"
error cwd /tmp/deployment/application
error node -v v0.10.26
error npm -v 1.4.4
error code ELIFECYCLE


and for bson-ext/builderror.log
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance


and for bson/builderror.log
gyp: binding.gyp not found (cwd: /Users/jeff/sandbox/testBuild/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jeff/sandbox/testBuild/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

**Comment by skyle143** [comment]
I forgot to mention that a workaround is to change this line: https://github.com/christkv/bson-ext/blob/master/package.json#L38 to:

'"install": "./node_modules/node-pre-gyp/bin/node-pre-gyp.js install --fallback-to-build",

and it builds fine.

Here is some more output that pointed me in that direction:

bson-ext@0.1.3 install /tmp/deployment/application/node_modules/mongo-deferred/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext
 > node-pre-gyp install --fallback-to-build

 module.js:338
     throw err;
           ^
 Error: Cannot find module '../'
     at Function.Module._resolveFilename (module.js:336:15)
     at Function.Module._load (module.js:278:25)
     at Module.require (module.js:365:17)
     at require (module.js:384:17)
     at Object.<anonymous> (/tmp/deployment/application/node_modules/mongo-deferred/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/node_modules/.bin/node-pre-gyp:15:20)
     at Module._compile (module.js:460:26)
     at Object.Module._extensions..js (module.js:478:10)
     at Module.load (module.js:355:32)
     at Function.Module._load (module.js:310:12)
     at Function.Module.runMain (module.js:501:10)

 npm ERR! Linux 3.14.35-28.38.amzn1.x86_64
 npm ERR! argv "/opt/elasticbeanstalk/node-install/node-v0.12.2-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v0.12.2-linux-x64/bin/npm" "--production" "rebuild"
 npm ERR! node v0.12.2
 npm ERR! npm  v2.7.4
 npm ERR! code ELIFECYCLE
 npm ERR! bson-ext@0.1.3 install: `node-pre-gyp install --fallback-to-build`
 npm ERR! Exit status 1
 npm ERR!
 npm ERR! Failed at the bson-ext@0.1.3 install script 'node-pre-gyp install --fallback-to-build'.
 npm ERR! This is most likely a problem with the bson-ext package,
 npm ERR! not with npm itself.
 npm ERR! Tell the author that this fails on your system:
 npm ERR!     node-pre-gyp install --fallback-to-build
 npm ERR! You can get their info via:
 npm ERR!     npm owner ls bson-ext
 npm ERR! There is likely additional logging output above.

 npm ERR! Please include the following file with any support request:
 npm ERR!     /tmp/deployment/application/npm-debug.log
 Not using a reverse proxy
 Running npm install:  /opt/elasticbeanstalk/node-install/node-v0.12.2-linux-x64/bin/npm
 Running npm with --production flag
 Failed to run npm install. Snapshot logs for more details.
 Traceback (most recent call last):
   File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 610, in <module>
     main()
   File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 592, in main
     node_version_manager.run_npm_install(options.app_path)
   File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 128, in run_npm_install
     self.npm_install(bin_path, self.config_manager.get_container_config('app_staging_dir'))
   File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 159, in npm_install
     raise e
 subprocess.CalledProcessError: Command '['/opt/elasticbeanstalk/node-install/node-v0.12.2-linux-x64/bin/npm', '--production', 'rebuild']' returned non-zero exit status 1 (Executor::NonZeroExitStatus)

**Comment by kmcclosk** [comment]
Thanks for this detailed write-up. I am troubled by exact same issue.

**Comment by imlucas** [comment]
@skyle143 thanks for chasing that down.  you're awesome! working on it.

**Comment by imlucas** [comment]
@jlines ok the `bson-ext/builderror.log` contents are a red herring.  think this might just be because it's being installed in mongoose and there is a `$PATH` error.
