### ISSUE TITLE
bson-ext fails to install

### ISSUE THREAD

**Issue by microscope** [christkv/bson-ext#13]
Dear Christkv:

Installing bson-ext fails. Here is the npm output towards the very end:
= = = = =
npm ERR!  Failed at the bson-ext@0.1.6 install script './node_modules/node-pre-gyp/bin/node-pre-gyp.js install --fallback-to-build'.
npm ERR! This is most likely a problem with the bson-ext package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/node-pre-gyp/bin/node-pre-gyp.js install --fallback-to-build
= = = = =
npm also suggests including the npm-debug.log, but I can't figure out how to attach that here.

The computer is a virtual machine (Vagrant) with plain-vanilla Ubuntu 14.04 LTS 64-bit server. 
Clean install of Nodejs v0.12.2 with npm 2.7.4 and MongoDB 3.0.2.
After that, Express, Sqlite3, Node-gyp all installed without a hitch. Node-pre-gyp 0.6.7 required glob@'^4.0.2', but otherwise installed fine. Nan is 1.8.4

I can't find any useful suggestions elsewhere on the web, and as a bit of an npm newbie I am stuck here.
I'd be happy to supply any other necessary information and be grateful for any help.

Thanks,

microscope

**Comment by igorklopov** [comment]
Try this fix manually: https://github.com/christkv/bson-ext/pull/15

**Comment by microscope** [comment]
"Windows does not work with shebang. So, explicit call to `node` is required"

Unfortunately, I am trying to install on Ubuntu Linux. Thanks though,

microscope

**Comment by alexmcmillan** [comment]
Just out of left field: have you tried `apt-get install build-essential` ?  I'm always forgetting that...

**Comment by microscope** [comment]
"Just out of left field: have you tried apt-get install build-essential ? I'm always forgetting that..."

Thanks for the suggestion. Yes, I had done that--the first few lines in the shell-script section of my Vagrantfile for provisioning were:

	config.vm.provision "shell", inline: <<-SHELL
		## update the package list
		sudo apt-get update
		
		## remove the package 'node' if installed -- it is for amateur radio and has
		# nothing to do with node.js, which is called 'nodejs' in Ubuntu/Linux
		sudo apt-get remove --purge node

		## install general build tools
		sudo apt-get install -y linux-headers-generic build-essential

**Comment by microscope** [comment]
Alright, I think I found a solution. It seems that once the node-gyp module is installed via npm, you need to run it by itself from the commandline before you continue with modules whose installation make use of it:

node-gyp install
 
After I did that, bson-ext and mongoose (which is what I really was after) installed just fine.

This extra step may be blatantly obvious to people who understand npm and node-gyp, but to a newbie like me it was not. (I wish I could credit where I found this nugget, but that is lost in the haze of ever-more desperate googling.)

For completeness, here is my entire install script for setting up a webserver with node, express, sqlite, mongodb, and mongoose in Ubuntu 14.04 LTS 64-bit server. This was part of provisioning a virtual machine in Vagrant, but you could run the relevant parts directly from the commandline:

#############################
		## ... initial sections of Vagrantfile up to here

		# Enable provisioning with a shell script. Additional provisioners such as
		# Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
		# documentation for more information about their specific syntax and use.
		config.vm.provision "shell", inline: <<-SHELL

		## update the package list
		sudo apt-get update
		
		## remove the package 'node' if installed -- it is for amateur radio and has
		# nothing to do with node.js, which is called 'nodejs' in Ubuntu/Linux
		sudo apt-get remove --purge node

		## install general build tools
		sudo apt-get install -y linux-headers-generic build-essential
		
		## install sqlite3 standalone (version in Ubuntu repository is quite recent)
		sudo apt-get install sqlite3

		## mongodb latest version 3.0.2 (repos have only 2.4.9) according to
		#  http://docs.mongodb.org/master/tutorial/install-mongodb-on-ubuntu/
		sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
		echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
		sudo apt-get update -y
		sudo apt-get install -y mongodb-org

		## install the current version of node.js from node repository via package manager
		# see https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager
		# and https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories
		curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -
		# sudo apt-get update -y	# not necessary -- part of script
		sudo apt-get install -y nodejs
		
		## install desired node modules via npm
		# Node.js native addon build tool
		sudo npm install -g node-gyp
		# Node.js native addon binary install tool
		sudo npm install -g node-pre-gyp
		# Fast, unopinionated, minimalist web framework		
		sudo npm install -g express
		# Asynchronous, non-blocking SQLite3 bindings
		sudo npm install -g sqlite3	

		# to get the bson-ext dependency during the mongoose install to work
		node-gyp install
		# a MongoDB object modeling tool designed to work in an asynchronous environment.
		sudo npm install -g mongoose
	SHELL
end
#############################
