### ISSUE TITLE
fails on iojs v2

### ISSUE THREAD

**Issue by jonathanong** [christkv/bson-ext#14]
the error messages are pretty annoying =/

**Comment by christkv** [comment]
can you please elaborate ?

**Comment by jonathanong** [comment]
i'm getting the following message after upgrading:

```
[Error: Module did not self-register.]
js-bson: Failed to load c++ bson extension, using pure JS version
```

let me add iojs v1 and 2 to the travis. if those pass, i'll be happy. it's currently failing though https://travis-ci.org/imlucas/bson-ext/jobs/61629492

**Comment by christkv** [comment]
that looks like you just built the extension on one version of node and then switched versions of node or iojs that does not support the v8 c++ api the extension was originally compiled against. you need to clean  NPM and recompile all the extensions with the new node/iojs runtime
