### ISSUE TITLE
FATAL: 0.1.9 breaks saving objects via collection.update()

### ISSUE THREAD

**Issue by leider** [christkv/bson-ext#21]
Hi,
when using latest mongodb, it pulls bson-ext in version 0.1.9.

This version breaks compatibility on collection.update()

Error message: 
The _id field cannot be changed from {_id: ObjectId('53d7f4902685068491efaffe')} to {_id: { _bsontype: "ObjectID", id: "S×ô&ï¯þ", generationTime: 1406661776 }}

OS: Mac OS (10.10.3)
Mongo: 2.6.10 (2.4.3 shows same behavior)

If any additional information wanted, contact me.

**Comment by christkv** [comment]
a code example reproducing it would be useful as well as knowing what exact version of the driver you are using as I cannot reproduce meaning there is something going on here outside of just normal serialization.

**Comment by leider** [comment]
Will try.

**Comment by leider** [comment]
updateing mongodb to "2.0.34" fixed the behavior
