### ISSUE TITLE
Node-pre-gyp dependency hard-coded to single version causing dedupe issues

### ISSUE THREAD

**Issue by dolkensp** [christkv/bson-ext#22]
Any Reason that the dependency is listed as 

"node-pre-gyp": "https://github.com/mongodb-js/node-pre-gyp/archive/v0.6.5-appveyor.tar.gz"

rather than a regular version number like other packages?

I understand if it has to be a specific version, but it's causing me headaches deduping long node package paths on windows currently...

**Comment by christkv** [comment]
not using node-pre-gyp anymore
