### ISSUE TITLE
Problem with https blocking proxy

### ISSUE THREAD

**Issue by olingerc** [christkv/bson-ext#24]
Because of paranoical settings of our company proxy I can't go to https addresses. I've set my npm registry to http://... and strict-ssl false and this is enough for most packages.
Unfortunately, bson-ext wants to install from https://github.com/mongodb-js/node-pre-gyp/archive/v0.6.5-appveyor.tar.gz.

Can I somehow manually install this from cache, or build myself? I've lost hours now getting this to work. All this node-pre-yp stuff is very obscure!
I tried setting up my own proxy, adding to cache, copying form another machine... but no luck. npm insists on downloading that file!!!

**Comment by christkv** [comment]
If you use the latest 2.0.x driver you do not need bson-ext. I would also recommend using the javascript bson parser instead

**Comment by olingerc** [comment]
Nice! That solves a lot of problems.
How do I tell my package.json to do just that? --no-optional? I currently have
```
"mongoose": "4.1.x",
```
in my package.json
.
Or would I explicitly put bson into my package.json and than mongoose would skip bson?

Thanks

**Comment by olingerc** [comment]
Maybe fixing https://github.com/christkv/bson-ext/issues/22 could solve my problem too? Using --no-optional works, but unfortunateyl this means I won't get any optionals at all for all packages.

**Comment by christkv** [comment]
I suggest opening a new ticket on the mongoose project

**Comment by christkv** [comment]
the problem is the mongoose dependency on the bson 0.3.x branch not the driver.
