### ISSUE TITLE
BSON.stringify slower than JSON.stringify?

### ISSUE THREAD

**Issue by vird** [christkv/bson-ext#25]
0.188 s
vs
0.049 s

**Comment by christkv** [comment]
is bson stringily something you wrote ? BSON will always be slower than JSON as it cheats in v8 and has optimizations unavailable for any js or c++ code.

**Comment by vird** [comment]
Ex. msgpack is only 2 times slower

**Comment by christkv** [comment]
msgpack also does not have to scan 0 terminated key names as it gives you the key size up front.
