### ISSUE TITLE
Use NAN v2

### ISSUE THREAD

**Issue by emersion** [christkv/bson-ext#26]
See https://github.com/nodejs/nan/issues/451#issuecomment-139736230

**Comment by guymguym** [comment]
:+1: 
@christkv Ay plans to release this or willing to accept PR?

**Comment by christkv** [comment]
I accept PRs

**Comment by globlee** [comment]
If anyone is working on this I can help

**Comment by guymguym** [comment]
this can be closed now that #27 is merged. thanks!
