### ISSUE TITLE
TypeError: bson.serialize is not a function

### ISSUE THREAD

**Issue by Dillybob92** [christkv/bson-ext#31]
Hey guys,

I just finished compiling the cc file into a .node file using node-gyp.

Here is my code:

```
var bson =  require('./bson/build/Release/bson.node');

console.log( bson.serialize() );
```

And I'm getting `TypeError: bson.serialize is not a function`

Which is weird because when I do:
`BSON = bson.BSON.prototype;`

I get access to all the functions, but they give invocation errors

```

BSON {
  calculateObjectSize: [Function: calculateObjectSize],
  serialize: [Function: serialize],
  serializeWithBufferAndIndex: [Function: serializeWithBufferAndIndex],
  deserialize: [Function: deserialize],
  deserializeStream: [Function: deserializeStream] }

```

Any idea guys? Can I get a working example of how you guys use it on your server?

**Comment by Dillybob92** [comment]
http://stackoverflow.com/a/36785924/1254837

Looks like we need to use

```
BSON = require('bson').native().BSON;
var newBSON = new bson();
console.log(newBSON.serialize('hello'));
```

Would of been nice for some documentation..  lol but I found it ;)

**Comment by christkv** [comment]
I'm curious what you are planning to use it for ?

**Comment by Dillybob92** [comment]
I am thinking about using it send/receive data through websockets 

The non-native `bson` works fine but I was trying to push out extra performance with the native binding one (here) -- but it seems like it's the same. I thought it was going to be faster.

**Comment by christkv** [comment]
latest version of the bson parser should be better it can be built using npm build

**Comment by hjisaac** [comment]
Many be you should do `BSON.prototype.serialize()`
