### ISSUE TITLE
Heap corruption when serializing more than 16 MB

### ISSUE THREAD

**Issue by gregmarr** [christkv/bson-ext#32]
In bson.h, DataStream member functions do this:

```
if((size_t)((p + 4) - destinationBuffer) > MAX_BSON_SIZE) throw "document is larger than max bson document size of 16MB";
```

Then in bson.cc, NAN_METHOD(BSON::SerializeWithBufferAndIndex) does this:
```
catch(char *exception) {
	Local<String> error = NanStr(exception);
	free(exception);
	return Nan::ThrowError(error);
} catch(const char *exception) {
	Local<String> error = NanStr(exception);
	return Nan::ThrowError(error);
}
```

The exception is caught in the first `catch` block, which calls `free` on `exception`.  Since `exception` was not allocated with `malloc`, this corrupts the heap.  It looks like there was an attempt to not call `free` on `exception` by having the `const char *` catch block, but that isn't working.  

platform: Windows 7
Installed by npm install of mongoose@4.0.5 => bson@0.3.2 => bson-ext@0.1.13

**Comment by christkv** [comment]
feel free to send a PR but be aware that never mongodb drivers no longer use the c++ extension.

**Comment by gregmarr** [comment]
Thanks, I'll see if we can upgrade.

**Comment by christkv** [comment]
also be aware that MongoDB does not accept documents bigger than 16MB

**Comment by gregmarr** [comment]
Thanks.  I learned about this limitation because of this crash, and we're exploring alternate methods of storage as well, but in the mean time, we'd like to not crash.  I'm looking at updating mongoose.

**Comment by gregmarr** [comment]
Mongoose latest is shown as using bson 0.4.23.  I don't see bson-ext listed as a dependency for that version. Does that mean that version will avoid this problem?

**Comment by gregmarr** [comment]
Looks like a yes.  Thanks for your help.
