### ISSUE TITLE
Dependency on old "nan" version in published package

### ISSUE THREAD

**Issue by SM6ZFA** [christkv/bson-ext#34]
Hello,

In the version of bson-ext (0.1.13) that is published to npm there is a dependency on nan 2.0.9 which in itself doesn't cause me any trouble, however when I do a clean npm install it somehow clashes with the installation of the package bufferutil which depends on nan 2.4.x.

If I manually install bufferutil before bson-ext there are no problems, but if bson-ext is installed first (which npm does due to its installation order which strictly follows the alphabet) it causes the bufferutil installation to fail due to the old nan package installed by bson-ext.

I solved this issue using a partial shrinkwrap to force bson-ext to depend on nan 2.4.0 instead, but seeing as partial shrinkwraps are no longer supported in npm 4.0.0 this is no lasting solution. However, bson-ext functioned fully and installed properly using nan 2.4.0 so I see no problem in slightly relaxing the dependencies in the package.json file and publishing a new version to npm.

Best regards!

**Comment by christkv** [comment]
Unfortunately in the past this has not held which is the reason the module is pinned to a specific version of nan. We are considering resurrecting the bson-ext package as I spoke with some users who have proven it makes a big difference in specific corner cases.

**Comment by christkv** [comment]
this has been fixed
