### ISSUE TITLE
/lib64/libc.so.6: version `GLIBC_2.14' not found

### ISSUE THREAD

**Issue by imlucas** [christkv/bson-ext#6]
See mapbox/node-sqlite3#244

> I'm trying to use node-mongdb-native on CentOS 6.6. When I run "npm install" I see these errors:

```
[Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /<rootfolder>/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release/bson.node)]

js-bson: Failed to load c++ bson extension, using pure JS version

[Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /<rootfolder>/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release/bson.node)]

js-bson: Failed to load c++ bson extension, using pure JS version

[Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /<rootfolder>/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release/bson.node)]

js-bson: Failed to load c++ bson extension, using pure JS version

[Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by <rootfolder>/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release/bson.node)]

js-bson: Failed to load c++ bson extension, using pure JS version
```

**Comment by christkv** [comment]
not sure we can skip supporting earlier version of linux

**Comment by imlucas** [comment]
Setting up centos 6.6 test env.

Plan is to modify [`node-pre-gyp install`](https://github.com/mongodb-js/node-pre-gyp/blob/master/lib/install.js#L119) to add an extra check for libc version.  So if you're running say centos 6.6, we'll switch to `npm install --build-from-source` that 

```javascript
var which = require('which');
var proc = require('child_process');

function hasOldLibC(fn){
 which('ldd', function(err, p){
   if(err) return fn(null, false);
   proc.exec(p + ' --version', function(err, stdout){
      if(err) return fn(err);
      var matches = /(\d{1})\.(\d{2})/.exec(stdout.toString('utf-8').split('\n')[0]);
      var minor = parseInt(matches[2], 10);
      if(minor <14) return fn(null, true);
      return fn(null, false);
   });
 });
}

...

var source_build = gyp.opts['build-from-source'] || gyp.opts.build_from_source;
var should_do_source_build = source_build === package_json.name || (source_build === true || source_build === 'true');
var no_rollback = gyp.opts.hasOwnProperty('rollback') && gyp.opts.rollback === false;
hasOldLibC(function(err, is_old_libc){
  if(err) return callback(err);

  if (should_do_source_build) {
     log.info('build','requesting source compile');
     return do_build(gyp,argv,callback);
  }
  else if(is_old_libc){
     log.info('build','requesting source compile because libc is old');
     gyp.opts['build-from-source'] = 1;
     return do_build(gyp,argv,callback);
  }
});

```

**Comment by christkv** [comment]
don't you think this going to get a bit complicated? I'm sure there are even more possible runtime issues that we have not though off.

**Comment by imlucas** [comment]
don't think it's more complicated than the alternative.  two parts to solving this before moving on to kerberos: 1. some variant of the above to fallback to `--build-from-source` even if there is a pre-built and 2. changing the message in `ext/index.js` to have clear instructions on reporting and to not panic.

**Comment by christkv** [comment]
kerberos won't be able to auto install as there is mit lib dependencies that will cause issues for sure as most people have to install those and versions vary so kerberos only makes sense to build for windows.

**Comment by imlucas** [comment]
@christkv ah ok so this is a good breakpoint.  I'll put together a PR that only publishes binaries for windows and we can circle back to this when Scout needs cross-platform kerberos.  Didn't know about the MIT lib deps.  Mind updating the README on christkv/kerberos with what they are and how to get them?

**Comment by christkv** [comment]
merged and published

**Comment by jgallen23** [comment]
Is there any way for me to define my own prebuilt binary for ubuntu?  Our builds are very slow because we use a lot of modules that require mongo, so bson-ext has to be compiled multiple times.

**Comment by imlucas** [comment]
@jgallen23 we're planning on it.  we've all just been swamped getting ready for [mongodb world](http://mongodbworld.com/) which starts tomorrow.  i really want ubuntu and osx binaries as well, but there are a lot of edge cases and tests we need to setup or else we'll just be creating exponentially more problems.
