### ISSUE TITLE
bson-ext@0.1.2 missing bundled node-pre-gyp

### ISSUE THREAD

**Issue by rmg** [christkv/bson-ext#8]
node-pre-gyp is listed as a bundledDependency, but it is not present in the [published tarball](http://registry.npmjs.org/bson-ext/-/bson-ext-0.1.2.tgz).

**Comment by christkv** [comment]
we don't bundle up the dependencies in the tar balls just as they are not in the npm module. you need to execute npm install

**Comment by rmg** [comment]
Not sure if anyone other than me still cares about this issue, but if npm/npm#8315 ever happens, it will block bson-ext from being published this way.

**Comment by imlucas** [comment]
@rmg I got you covered.  Ping me if there's ever an issue here.
