### ISSUE TITLE
./Release/.deps/Release/obj.target/bson/ext/bson.o.d.raw: No such file or directory compilation terminated

### ISSUE THREAD

**Issue by skotchio** [christkv/bson-ext#9]
Since yesterday I get the following error:

    ./Release/.deps/Release/obj.target/bson/ext/bson.o.d.raw: No such file or directory compilation terminated

Here is the full stack trace:

`make: Entering directory /var/www/.tmp/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
  4567 Killed                  npm install --production
04/24/15 00:15:11 ::  Error: Could not install all npm dependencies
$ ../ext/bson.cc:1072:36: fatal error: opening dependency file ./Release/.deps/Release/obj.target/bson/ext/bson.o.d.raw: No such file or directory
compilation terminated.
make: *** [Release/obj.target/bson/ext/bson.o] Error 1`

`make: Leaving directory /var/www/.tmp/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build`

`gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-43-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/var/www/.tmp/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release/bson.node" "--module_name=bson" "--module_path=/var/www/.tmp/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release"
gyp ERR! cwd /var/www/.tmp/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok`

`node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/var/www/.tmp/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release/bson.node --module_name=bson --module_path=/var/www/.tmp/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/www/.tmp/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Linux 3.13.0-43-generic
node-pre-gyp ERR! command "node" "/var/www/.tmp/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /var/www/.tmp/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext
node-pre-gyp ERR! node -v v0.12.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok ` 

`Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/var/www/.tmp/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release/bson.node --module_name=bson --module_path=/var/www/.tmp/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release' (1)`

Please help me. What is the problem?

**Comment by christkv** [comment]
most likely it worked for you yesterday because it pulled down a pre-built binary. However these have serious problems for linux we discovered as they break depending on your glib version. What I suggest is that you clone the repo locally

```
git clone https://github.com/christkv/bson-ext.git
cd bson-ext
npm install
make test
```

if your buid environment is not correctly set up this will break. you should then look at this page.

http://christiankvalheim.com/post/diagnose_installation_problems/

**Comment by imlucas** [comment]
@skotchio mind posting your OS and OS version?  As well, could you run `node -p process.versions`?  With that info, we can test this on our end and get it sorted for you.

**Comment by skotchio** [comment]
@imlucas sorry for the issue. The problem was in low RAM
